### ISSUE TITLE
Problem with `#`

### ISSUE THREAD

**Issue by erkal** [brandly/elm-dot-lang#3]
Hi brandly, [this line](https://github.com/brandly/elm-dot-lang/blob/657bda40d480a21eb4c6b0a33fb2734600851a32/src/DotLang.elm#L469) prevents me to have colors[ in hex format as GraphViz does](https://www.graphviz.org/doc/info/attrs.html#k:color)

**Comment by brandly** [comment]
see my comment on #5. i think the solution i described there should fix this as well.

i [added a failing test](https://github.com/brandly/elm-dot-lang/commit/710c0bd293747ee40e438c9714ab291c9f049148). it looks like we can parse `#` inside quotes, but `toString` outputs the color with no quotes.

thanks for filing these issues!
